### ISSUE TITLE
Provides a way to configure a router

### ISSUE THREAD

**Issue by sicardnicolas** [vadept/vachettp#11]
A router should read a configuration file (yaml, toml, younameit) to link endpoints to files and functions.

Example:
```
routes:
  index:
    method: GET # default value
    path: '/index'
    file: './controllers/index.v'
    method: index

  get_stuff:
    method: GET
    path: '/products'
    file: './products/infrastructure/controller.v'
    method: list
```
